### ISSUE TITLE
"Class does not exist" error

### ISSUE THREAD

**Issue by brettscott** [lphuberdeau/Neo4j-PHP-OGM#51]
I've been trying to setup OGM v2.0.0 for the last day without any luck.

I'm receiving the following error:

```
Class does not exist
500 Internal Server Error - ReflectionException 
In ...\vendor\hirevoice\neo4jphp-ogm\lib\HireVoice\Neo4j\Meta\Entity.php at line 41
```

Graph data:

```
CREATE (a1:Test {title:'a1'})
CREATE (b1:Test {title:'b1'})
CREATE (c1:Test {title:'c1'})
CREATE (d1:Test {title:'d1'})
...
```

The following code resides within a Symfony2 Controller Action:

```
$em = $this->get('neo4j.manager');
$repository = $em->getRepository('\\Path\\To\\Entity\\Test');
$query = $em->createCypherQuery()
    ->match('(t:Test)')
    ->end('t');
$list = $query->getList();
return $list->first()->getTitle();
```

Symfony2 config.yml:

```
services:
    neo4j.manager:
        class: "HireVoice\\Neo4j\\EntityManager"
        arguments:
            -
                host: "localhost"
                port: 7474
                annotation_reader: @annotation_reader
```

The "Test" entity which maps to the "Test" label nodes:

```
<?php
namespace Path\To\Entity;

use HireVoice\Neo4j\Annotation as OGM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @OGM\Entity
 */
class Test
{
    /**
     * @OGM\Auto
     */
    protected $id;

    /**
     * @OGM\Property
     * @OGM\Index
     */
    protected $title;

    public function setTitle($comments)
    {
        $this->title = $comments;

        return $this;
    }

    public function getTitle()
    {
        return $this->title;
    }
}
```

After reading the code, unit tests and seeing the issue raised in confoo-demo (https://github.com/lphuberdeau/confoo-demo/issues/1), I can see that adding a property "class" with the value "Path\To\Entity\Test" to each of the nodes within the graph will make it work.  It appears that OGM cannot determine the entity to deserialise to.

Is there a better way? Am I doing something wrong? Is there a demo application which follows OGM best practices?
